boat-diff/pom.xml
boat-engine/pom.xml
boat-engine/src/main/java/com/backbase/oss/boat/Exporter.java
boat-engine/src/main/java/com/backbase/oss/boat/JsonSchemaToOpenApi.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/AdditionalPropertiesAdder.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/LicenseAdder.java
boat-maven-plugin/README.md
boat-maven-plugin/pom.xml
boat-maven-plugin/src/main/java/com/backbase/oss/boat/AbstractRamlToOpenApi.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/ExportBomMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/ExportMojo.java
boat-terminal/pom.xml
pom.xml

Added option to disable Java Type Extensions

Semver versioning

---

boat-terminal/pom.xml

This issue was found when running BoatTerminal as follows:
```
java -jar target/boat-terminal-0.0.1-SNAPSHOT-jar-with-dependencies.jar \
-f src/test/resources/api.raml
```
The following error occurred:
`Error: Could not find or load main class com.backbase.oss.BoatTerminal`
This fixes the error.

Corrected the main class for BoatTerminal

---

README.md
boat-maven-plugin/src/main/java/com/backbase/oss/boat/CodeGenMojo.java
boat-maven-plugin/src/main/templates/JavaSpring/api.mustache

Functionality extracted from this PR https://github.com/OpenAPITools/openapi-generator/pull/4269
Adding useClassLevelBeanValidation configuration option for conditionally adding the Validated annotation to the generated API interfaces
It defaults to false

Adding useClassLevelBeanValidation configuration option

---

README.md
boat-maven-plugin/src/main/java/com/backbase/oss/boat/CodeGenMojo.java
boat-maven-plugin/src/main/templates/JavaSpring/api.mustache

add configuration option to enable the addition of HttpServletRequest objects to API definition methods
`addServletRequest` will be defaulted to false. When enabled, it will add a HttpServletRequest object to the API interface methods
For a better view of my changes in the Template, an expanded view
```
{{#allParams}}
{{>queryParams}}
{{>pathParams}}
{{>headerParams}}
{{>bodyParams}}
{{>formParams}}
{{#hasMore}},{{/hasMore}}
{{^hasMore}}
{{#reactive}}, {{/reactive}}
{{^reactive}}
{{#addServletRequest}}, {{/addServletRequest}}
{{/reactive}}
{{/hasMore}}
{{/allParams}}
{{#addServletRequest}}
HttpServletRequest httpServletRequest
{{#reactive}}, {{/reactive}}
{{/addServletRequest}}
{{#reactive}}ServerWebExchange exchange{{/reactive}}
```

Add configuration option to enable the addition of HttpServletRequest objects to API definition methods

---

boat-engine/pom.xml

#19 
`java.lang.NoSuchMethodError: org.yaml.snakeyaml.events.MappingStartEvent`
An 1.15 version of org.yaml:snakeyaml was used in runtime. When it is used as CLI maven-assembly-plugin was copying that dependency when creating **jar-with-dependencies**.
This PR override runtime dependency for org.yaml:snakeyaml with 1.24 version instead of 1.15 version.

Override runtime dependency for org.yaml:snakeyaml with 1.24 

---

README.md
boat-engine/src/main/java/com/backbase/oss/boat/transformers/Bundler.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/bundler/BoatCache.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/bundler/BoatOpenAPIResolver.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/bundler/ExampleHolder.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/bundler/ExamplesProcessor.java
boat-engine/src/test/java/com/backbase/oss/boat/transformers/BundlerTest.java
boat-engine/src/test/resources/openapi/bundler-examples-test-api/examples/user-post-request-2.json
boat-engine/src/test/resources/openapi/bundler-examples-test-api/examples/user-post-request.json
boat-engine/src/test/resources/openapi/bundler-examples-test-api/examples/user-post-response-2.json
boat-engine/src/test/resources/openapi/bundler-examples-test-api/examples/user-post-response.json
boat-engine/src/test/resources/openapi/bundler-examples-test-api/examples/user-post-response.xml
boat-engine/src/test/resources/openapi/bundler-examples-test-api/lib/examples/bad-request-validation-error.json
boat-engine/src/test/resources/openapi/bundler-examples-test-api/lib/schema/bad-request-error.yaml
boat-engine/src/test/resources/openapi/bundler-examples-test-api/lib/schema/error-item.yaml
boat-engine/src/test/resources/openapi/bundler-examples-test-api/openapi.yaml
boat-engine/src/test/resources/openapi/bundler-examples-test-api/schemas/components.yaml
boat-engine/src/test/resources/openapi/bundler-examples-test-api/schemas/post-user-request.json
boat-engine/src/test/resources/openapi/bundler-examples-test-api/schemas/post-user-response.json
boat-maven-plugin/README.md
boat-maven-plugin/pom.xml
boat-maven-plugin/src/main/java/com/backbase/oss/boat/BundleMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/ValidateMojo.java

`boat:bundle` now also picks up examples.
`boat:bundle` can be used to process multiple specs in one execution.
`boat:validate` can be used to validate multiple specs in one execution.

boat-maven-plugin bundler dereferences examples (and other fixes)

---

boat-maven-plugin/src/main/java/com/backbase/oss/boat/BundleMojo.java
boat-maven-plugin/src/test/java/com/backbase/oss/boat/BundleMojoTest.java
boat-maven-plugin/src/test/resources/bundler/folder/another-client-api-v1.yaml
boat-maven-plugin/src/test/resources/bundler/folder/one-client-api-v1.yaml
boat-maven-plugin/src/test/resources/bundler/folder/one-client-api-v2.yaml

Bundler can now generate filename(s) that reflect the full semver version in the file name.
For instance `payment-order-client-api-v2.yaml` -> `payment-order-client-api-v2.1.48.yaml`
Includes checking the major version number in the file name matches the one in the api.

Generate filename using open api info.version

---

boat-engine/src/main/java/com/backbase/oss/boat/transformers/Bundler.java
boat-engine/src/test/java/com/backbase/oss/boat/transformers/BundlerTest.java

html2 generator was ignoring simple types defined as components/schema - other generators have trouble processing inlined types.

UnAliassing was needed for html generator, but breaks client generators.

---

.github/workflows/build.yml
README.md
boat-engine/pom.xml
boat-engine/src/main/java/com/backbase/oss/boat/transformers/bundler/BoatCache.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/bundler/BoatDeserializationUtils.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/bundler/BoatOpenAPIResolver.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/bundler/ExampleHolder.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/bundler/ExamplesProcessor.java
boat-engine/src/test/java/com/backbase/oss/boat/transformers/BundlerTest.java
boat-maven-plugin/pom.xml
boat-maven-plugin/src/main/java/com/backbase/oss/boat/BundleMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/GenerateMojo.java
boat-maven-plugin/src/test/java/com/backbase/oss/boat/BundleMojoTest.java
boat-maven-plugin/src/test/java/com/backbase/oss/boat/GeneratorTests.java
boat-quay/boat-quay-lint/pom.xml
boat-quay/boat-quay-rules/pom.xml
boat-quay/pom.xml
boat-scaffold/pom.xml
boat-scaffold/src/main/java/com/backbase/oss/codegen/doc/BoatCodegenParameter.java
boat-scaffold/src/main/java/com/backbase/oss/codegen/doc/BoatCodegenResponse.java
boat-scaffold/src/main/java/com/backbase/oss/codegen/doc/BoatDocsGenerator.java
boat-scaffold/src/main/java/com/backbase/oss/codegen/doc/BoatExampleUtils.java
boat-scaffold/src/main/templates/boat-docs/paramB.mustache
boat-scaffold/src/main/templates/boat-docs/response.mustache
boat-scaffold/src/main/templates/boat-docs/styles.mustache
boat-terminal/pom.xml
boat-trail-resources/pom.xml
pom.xml
tests/pom.xml

Handle API Responses correctly
Avoid stack overflow when parsing Example objects

Dereference Exotic Examples

---

boat-engine/src/main/java/com/backbase/oss/boat/transformers/bundler/BoatOpenAPIResolver.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/bundler/ExamplesProcessor.java
boat-engine/src/test/java/com/backbase/oss/boat/transformers/BundlerTest.java

Swagger example processor messes up the example contents.
Process Examples before swagger does.

Swagger example processor messes up examples.

---

boat-engine/src/main/java/com/backbase/oss/boat/transformers/bundler/ExampleHolder.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/bundler/ExamplesProcessor.java
boat-engine/src/test/java/com/backbase/oss/boat/transformers/BundlerTest.java
boat-engine/src/test/resources/openapi/bundler-examples-test-api/examples/user-post-request-3.json
boat-engine/src/test/resources/openapi/bundler-examples-test-api/openapi.yaml

When the spec has this
```
example:
value:
$ref: examples/client-api/v2/contacts-get.json
```
Avoid generating
```
example:
value:
$ref: examples/client-api/v2/contacts-get.json
$ref: '#/components/examples/example'
```
instead generate
```
example:
$ref: '#/components/examples/example'
```

Remove invalid value. after resolving example.

---

boat-scaffold/src/main/templates/boat-java/libraries/resttemplate/ApiClient.mustache

When providing configuration like so: 
```
<configuration
...
<additionalProperties>
restTemplateBeanName=interServiceRestTemplate
</additionalProperties>
</configuration>
```
There are compilation errors, this PR resolves them.
* Missing import
* Missing quotemarks for qualifier. Providing quotemarks in pom config escapes to `&quot;` so it's best to solve here.

Correct the import and use of @Qualifier in ApiClient template

---

boat-engine/src/main/java/com/backbase/oss/boat/transformers/bundler/ExamplesProcessor.java
boat-engine/src/test/java/com/backbase/oss/boat/transformers/BundlerTests.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/GenerateMojo.java
boat-maven-plugin/src/test/java/com/backbase/oss/boat/GenerateMojoTests.java
boat-maven-plugin/src/test/java/com/backbase/oss/boat/GeneratorTests.java
boat-scaffold/src/test/java/com/backbase/oss/codegen/java/BoatSpringCodeGenTests.java
boat-scaffold/src/test/java/com/backbase/oss/codegen/java/BoatSpringTemplatesTests.java
pom.xml

Support using the tools on Windows.
Key changes:
* It happens with the Unix FilesSystemProvider that http URLs parse as a valid java.nio.file.Path this is not the case on Windows, as we are using Path for relative path resolution I have changed this to use URI.
(Consider if this this still supports the required input values, such as any which are not parseable as a URI, all tests pass though).
* nul is a reserved file name on Windows and cannot be created, altered some tests.
* Updated assertions which check to use \n to use %n.

Support building the project on Microsoft Windows.

---

boat-maven-plugin/README.md
boat-maven-plugin/src/main/java/com/backbase/oss/boat/AbstractLintMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/BundleMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/GenerateRestTemplateEmbeddedMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/GenerateSpringBootEmbeddedMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/GenerateWebClientEmbeddedMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/LintMojo.java

- Adding new goal `lint` on the README.md file.
- Improve documentation of goals when using 
`mvn help:describe -DgroupId=com.backbase.oss -DartifactId=boat-maven-plugin -Ddetail `
_`help:describe` takes documentation from Javadoc on Mojo classes and parameters._

fix: Improve documentation when `mvn help:describe` 

---

boat-scaffold/src/main/templates/boat-docs/css_jsontreeviewer.mustache

The json viewer would span the page to close to an infinite width on examples with a property containing any long un-espaced text like a base64.
Just adding word-wrap fixes the issue.

Fixe page width going to infinity  on base64 long strings

---

boat-scaffold/src/main/java/com/backbase/oss/codegen/angular/BoatAngularGenerator.java
boat-scaffold/src/main/templates/boat-angular/package.mustache

This adds support for Angular 11 but we are not ready to default to it yet.
The support doesn't require many changes as the `ngVersion` property is already available, but there are a couple of related dependencies that are also required to be compatible. 
If we intend to maintain support for a number of previous versions this is probably a good candidate for refactoring into a data structure to represent the compatibility table instead of a chain of `if`s.

Add support for Angular 11

---

README.md
boat-engine/src/main/java/com/backbase/oss/boat/loader/OpenAPILoader.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/ExtensionFilter.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/SetVersion.java
boat-engine/src/test/java/com/backbase/oss/boat/transformers/ExtensionFilterTests.java
boat-maven-plugin/README.md
boat-maven-plugin/pom.xml
boat-maven-plugin/src/main/java/com/backbase/oss/boat/BundleMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/transformers/Merge.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/transformers/Prefix.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/transformers/Regex.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/transformers/Suffix.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/transformers/TransformMojo.java
boat-maven-plugin/src/test/java/com/backbase/oss/boat/transformers/TransformMojoTest.java
boat-scaffold/src/main/templates/boat-spring/model.mustache
boat-scaffold/src/main/templates/boat-spring/pojo.mustache
pom.xml

1. New boat:transform goal to pipeline existing transformers in an execution; works with multiple inputs
2. Use vendor extensions to inject arbitrary Java code in models generated by Spring generator

boat:transform

---

boat-maven-plugin/src/main/java/com/backbase/oss/boat/GenerateMojo.java
boat-scaffold/README.md
boat-scaffold/src/main/java/com/backbase/oss/codegen/java/BoatJavaCodeGen.java
boat-scaffold/src/main/java/com/backbase/oss/codegen/java/BoatSpringCodeGen.java
boat-scaffold/src/main/templates/boat-java/libraries/resttemplate/api.mustache
boat-scaffold/src/main/templates/boat-java/pojo.mustache
boat-scaffold/src/main/templates/boat-spring/pojo.mustache
boat-scaffold/src/test/java/com/backbase/oss/codegen/java/BoatJavaCodeGenTests.java
boat-scaffold/src/test/java/com/backbase/oss/codegen/java/BoatSpringCodeGenTests.java

- added `createApiComponent` (defaults to true)
- added `useProtectedFields`
- updated README

Added more configurations

---

boat-maven-plugin/README.md

Added example of how to use artifact input and where it is implemented to README

Fix: added documentation for artifact input feature

---

boat-scaffold/src/main/templates/boat-marina/api.js.handlebars

Since the output is a JS module, we need to export the data to be able to use it.

Adds missing export

---

README.md
boat-scaffold/src/main/templates/boat-angular/api.service.mustache

Added JSDoc comments to all overloads of operation functions in typescript client

---

boat-engine/src/main/java/com/backbase/oss/boat/transformers/Decomposer.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/GenerateFromDirectoryDocMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/GenerateMojo.java
boat-scaffold/src/main/java/com/backbase/oss/codegen/doc/BoatExampleUtils.java
boat-scaffold/src/test/java/com/backbase/oss/codegen/doc/BoatDocsTest.java
boat-scaffold/src/test/resources/logback.xml
boat-scaffold/src/test/resources/oas-examples/petstore-example-refs.yaml

Resolve references to other path operations' examples (as created by swagger-cli) 
eg `#/paths/~1client-api~1v2~1accounts~1balance-history~1%7BarrangementIds%7D/get/responses/200/content/text~1csv/example`
(fixes: #226)

Resolve references to other path operations' examples

---

README.md
boat-scaffold/src/main/java/com/backbase/oss/codegen/doc/BoatExampleUtils.java
boat-scaffold/src/test/resources/oas-examples/petstore-example-refs.yaml

Responses can have multiple examples, the previous fix assumed it only had one.

Fix reference to /examples/foo

---

boat-maven-plugin/README.md
boat-maven-plugin/pom.xml

This will negate the https://github.com/Backbase/backbase-openapi-tools/pull/236/files from dependency bot. for some reason the generated sources has errors in 5.1.0.
Updated to use the parent version.

Version update

---

boat-maven-plugin/src/main/java/com/backbase/oss/boat/BundleMojo.java
boat-maven-plugin/src/test/java/com/backbase/oss/boat/BundleMojoTest.java

Fix for https://github.com/Backbase/backbase-openapi-tools/issues/242
Improve the error message when the api version in the file cannot be parsed.

Improve the error message.

---

README.md
boat-engine/pom.xml
boat-maven-plugin/README.md
boat-maven-plugin/pom.xml
boat-maven-plugin/src/main/java/com/backbase/oss/boat/BundleMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/radio/RadioMojo.java
boat-maven-plugin/src/test/java/com/backbase/oss/boat/BundleMojoTest.java
boat-maven-plugin/src/test/java/com/backbase/oss/boat/radio/RadioMojoTests.java
boat-quay/boat-quay-lint/pom.xml
boat-quay/boat-quay-rules/pom.xml
boat-quay/pom.xml
boat-scaffold/pom.xml
boat-terminal/pom.xml
boat-trail-resources/pom.xml
pom.xml
tests/pom.xml

Getting version conflict when creating main->release PR. (Probably because the release branch was not merged back to main during the last release).
version-update-0.15.1-snapshot branch is just a brach created vis github UI while resolving conflitcs during main->release PR.

Release 0.15.1

---

boat-scaffold/src/main/templates/boat-java/libraries/resttemplate/ApiClient.mustache
boat-scaffold/src/main/templates/boat-java/libraries/webclient/ApiClient.mustache

A fix for mapping of Map for query params (in client code). You can have Map in query params when using additionalProperties. In current version generated client code throws an exception. This is a fix for it.

Fixed query param mapping for Maps.

---

boat-scaffold/src/main/java/com/backbase/oss/codegen/angular/BoatAngularGenerator.java
boat-scaffold/src/main/templates/boat-angular/package.mustache
boat-scaffold/src/test/java/com/backbase/oss/codegen/angular/BoatAngularTemplatesTests.java

ng-packagr have removed support for providing config via package.json.  Genereate ng-package.json file instead.

Generate ng-package.json file and remove ng-packagr config from package.json

---

boat-scaffold/src/main/java/com/backbase/oss/codegen/doc/BoatExampleUtils.java

People have complained about autogenerated examples from schema even though when they provide their own.
This PR adds a check, if there are examples present then we don't add the autogenerated one.

Does not create example from schema if there are examples present

---

boat-maven-plugin/pom.xml
boat-maven-plugin/src/it/example/boat-generate/angular/pom.xml
boat-maven-plugin/src/test/java/com/backbase/oss/boat/GeneratorTests.java
boat-quay/boat-quay-rules/pom.xml
boat-scaffold/pom.xml
boat-scaffold/src/main/java/com/backbase/oss/codegen/angular/BoatAngularGenerator.java
boat-scaffold/src/main/java/com/backbase/oss/codegen/marina/BoatHandlebarsEngineAdapter.java
boat-scaffold/src/main/templates/boat-angular/package.mustache
package-lock.json
pom.xml

Change:
Specify boat-angular ngVersion via range `>={{ngVersion}}` to support Angular version greater than range.

boat-angular update ngVersion to use >= range in dependencies

---

boat-maven-plugin/src/it/example/pom.xml
boat-maven-plugin/src/main/java/com/backbase/oss/boat/radio/RadioMojo.java
boat-scaffold/src/main/templates/boat-spring/libraries/spring-boot/pom.mustache

- fixed ObjectMapper in `radio` goal
- latest dependencies
Full error from Jenkins:
```
[INFO] [jenkins-event-spy] Generated /opt/fsroot/workspace/Cardiff/BBT/building-blocks-test-wallet/boat-plugin-version@tmp/withMaven5e09333c/maven-spy-20220801-134826-5065350269485296098564.log
[ERROR] Failed to execute goal com.backbase.oss:boat-maven-plugin:0.16.0:radio (upload-to-boat-bay) on project building-blocks-test-wallet-presentation-service: Failed to write output: Java 8 date/time type `java.time.OffsetDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: java.util.ArrayList[0]->com.backbase.oss.boat.bay.client.model.BoatLintReport["spec"]->com.backbase.oss.boat.bay.client.model.BoatSpec["createdOn …
```

java17 uplift and fixes

---

boat-scaffold/src/main/java/com/backbase/oss/codegen/angular/BoatAngularGenerator.java
boat-scaffold/src/test/java/com/backbase/oss/codegen/angular/BoatAngularTemplatesTests.java

BoatAngularGenerator: add dependency versions to support `angular@13`. The compatible peer dependency versions were found in the following resources:
- **RxJS version**: https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3
- **TypeScript version**: https://github.com/angular/angular/releases?expanded=true&page=5&q=13#:~:text=TypeScript%20versions%20older%20than%204.4.2%20are%20no%20longer%20supported. 
- **NG-PACKAGR version**: https://github.com/ng-packagr/ng-packagr/blob/1a503338c623ad1dfefc379067b8637daa19f901/package.json#L3-L71
Fixes # nojira

BoatAngularGenerator: add dependency versions for ang@13

---

README.md
boat-maven-plugin/src/main/java/com/backbase/oss/boat/GenerateMojo.java

Splitting on spaces causes issues where a value contains a legitimate space.
For example, an operation could have a tag with a space in it.  Passing that tag to the `apisToGenerate` config property causes it to be interpreted as two separate tags and therefore it is omitted from the generated APIs.

Do not split on spaces for properties which take a comma-separated list of values

---

boat-scaffold/src/main/java/com/backbase/oss/codegen/angular/BoatAngularGenerator.java

Unlike npm, there is no requirement for maven artifacts to follow any particular versioning strategy, so therefore no guarantee a spec artifact version is a valid semver version.

Treat specVersion as an opaque string, not a semver version

---

README.md
boat-scaffold/src/main/templates/boat-angular-mock/tsconfig.mustache
boat-scaffold/src/main/templates/boat-angular/tsconfig.mustache

Prevents the removal of the `/*#__PURE__*/` comments in the compiled output.

Set removeComments=false in generated tsconfig.json files

---

boat-maven-plugin/src/it/example/boat-generate/angular/pom.xml
boat-maven-plugin/src/test/java/com/backbase/oss/boat/LintMojoTests.java
boat-quay/boat-quay-rules/src/main/kotlin/com/backbase/oss/boat/quay/ruleset/EndpointAccessControlDefinedRule.kt
boat-quay/boat-quay-rules/src/test/kotlin/com/backbase/oss/boat/quay/ruleset/EndpointAccessControlDefinedRuleTest.kt

For each endpoint, what permissions are required should be defined, or it should explicitly state that access control is not enforced.

Add rule to enforce access-control specification for endpoints.

---

README.md
boat-scaffold/src/main/java/com/backbase/oss/codegen/angular/BoatAngularGenerator.java
boat-scaffold/src/main/templates/boat-angular/licenseInfo.mustache

* Use Array instead of Set by default for backwards compatibility with 0.16.x
* Add a fixed "generated code" comment at the start of every file so that API report diffs do not show "(undocumented}" everywhere (otherwise the PR updating data-ang to this version of BOAT will be polluted with thousands of irrelevant changes in the API reports)

Angular b/w compatibility

---

boat-scaffold/src/main/templates/boat-java/pojo.mustache
boat-scaffold/src/main/templates/boat-spring/pojo.mustache

With every openapi-generator bump, we should review the mustache templates. Those templates which contain custom changes like `useLombokAnnotations` are more prone to error with new updates. In this PR pojo templates have been updated.

align pojo mustache templates with openapi 6.6.0

---

README.md
boat-engine/src/main/java/com/backbase/oss/boat/transformers/bundler/ExampleHolder.java
boat-engine/src/test/resources/openapi/bundler-examples-test-api/openapi.yaml

According to open api spec, the single example on a media type can be Any type.  eg
```
/users:
get:
responses:
'200':
content:
csv:
example: |-
UserId,Username 
aaaa-bbbb-cccc,John
```
When the spec contains a string value, the bundling (or code generation) could fail with
```
[ERROR] com.backbase.oss.boat.transformers.TransformerException: Unknown type backing example java.lang.String
at com.backbase.oss.boat.transformers.bundler.ExampleHolder.of (ExampleHolder.java:167)
at com.backbase.oss.boat.transformers.bundler.ExamplesProcessor.processMediaType (ExamplesProcessor.java:115) <...>
```

Fix single, string typed example on media type

---

README.md
boat-scaffold/src/main/java/com/backbase/oss/codegen/BoatDefaultGenerator.java
boat-scaffold/src/main/java/com/backbase/oss/codegen/java/BoatCodeGenUtils.java
boat-scaffold/src/main/java/com/backbase/oss/codegen/java/BoatJavaCodeGen.java
boat-scaffold/src/main/java/com/backbase/oss/codegen/java/BoatSpringCodeGen.java
boat-scaffold/src/test/java/com/backbase/oss/codegen/java/BoatCommonJavaCodeGenTests.java
boat-scaffold/src/test/java/com/backbase/oss/codegen/java/BoatSpringCodeGenTests.java
boat-scaffold/src/test/resources/boat-spring/openapi.yaml

Generate proper initialization for arrays depending on
- containerDefaultToNull
- if field is required 
- if values are unique (set)

Bugfix: BoatJavaCodeGen and BoatSpringCodeGen -

---

README.md
boat-scaffold/src/main/java/com/backbase/oss/codegen/java/BoatSpringCodeGen.java
boat-scaffold/src/main/templates/boat-spring/api.mustache
boat-scaffold/src/main/templates/boat-spring/collectionDataType.mustache
boat-scaffold/src/main/templates/boat-spring/collectionDataTypeParam.mustache
boat-scaffold/src/main/templates/boat-spring/mapDataType.mustache
boat-scaffold/src/main/templates/boat-spring/optionalDataType.mustache
boat-scaffold/src/main/templates/boat-spring/pojo.mustache
boat-scaffold/src/test/java/com/backbase/oss/codegen/java/BoatSpringCodeGenTests.java
boat-scaffold/src/test/java/com/backbase/oss/codegen/java/BoatSpringTemplatesTests.java
boat-scaffold/src/test/resources/boat-spring/openapi.yaml

This PR fixes https://github.com/Backbase/backbase-openapi-tools/issues/622
Changes:
- added `collectionDataTypeParam.mustache` to fix missing validation constraints on request params
- added `mapDataType.mustache` to fix missing validation constraints on map field
- additionally improved formatting of touched templates and formatting of generated code

Add validation on request params and map types

---

README.md
boat-scaffold/src/main/templates/boat-spring/collectionDataType.mustache
boat-scaffold/src/test/resources/boat-spring/openapi.yaml

Fixes: https://github.com/Backbase/backbase-openapi-tools/issues/647

Add {} to avoid escaping <>

---

README.md
boat-maven-plugin/src/main/java/com/backbase/oss/boat/DiffMojo.java

Fix typo in `changelogRenderer` parameter in _DiffMojo_ class of the Maven plugin.
Fixes Backbase/backbase-openapi-tools#211

Issue 211: Fix typo in changelogRenderer parameter in DiffMojo

---

boat-engine/src/main/java/com/backbase/oss/boat/transformers/bundler/ExampleHolder.java
boat-scaffold/src/main/templates/boat-spring/api.mustache

Ticket: https://backbase.atlassian.net/browse/EACMR-612
Fixing issues caused by the SSDK 16 upgrade. 
1. Added support for byte[] example.
2. Removed Tag import so we can name a generated object Tag as we did before SSDK 16.

EACMR-612: Allow byte[] example and removed tag import

---

README.md
boat-scaffold/src/main/templates/boat-java/libraries/resttemplate/ApiClient.mustache
boat-scaffold/src/main/templates/boat-java/libraries/resttemplate/api.mustache
boat-scaffold/src/test/java/com/backbase/oss/codegen/java/BoatJavaCodeGenTests.java

Fix @Component for RestTemplate ApiClient

---

boat-maven-plugin/src/main/java/com/backbase/oss/boat/GenerateMojo.java
boat-scaffold/src/main/java/org/openapitools/codegen/languages/BoatSwift5Codegen.java
boat-scaffold/src/main/templates/boat-swift5/api_operation_parameter_model.mustache
boat-scaffold/src/test/java/com/backbase/oss/codegen/java/BoatSpringCodeGenTests.java
boat-scaffold/src/test/java/org/openapitools/codegen/languages/BoatSwift5CodegenTests.java

API Specs with properties defined with the type `object` a.k.a free form objects always have child properties with types defined clearly. 
In the event that these child properties do not have types defined explicitly, it is expected that the definition of the parent will have a property called `additionalProperties` [read more](https://swagger.io/docs/specification/data-models/dictionaries/).
This PR seeks to intervene the scenario where by the child properties don't have types and no `additionalProperties` exists.

Fix/Free-Form Object issue

---

boat-maven-plugin/src/it/example/boat-generate/angular/pom.xml

Bumps angular version from 13.0.0 to 16.2.6

Bump angular:boat-maven-plugin[boat-generate/angular] from 13.0.0 to 16.2.6

---

pom.xml

Examples of failures in services builds:
https://jenkins.backbase.eu/job/Entitlements/job/AG/job/accessgroup-integration-service/job/SEGM-558-migrate-to-boat/2/
https://jenkins.backbase.eu/blue/organizations/jenkins/F5%2FFX%2Fforex-test-client/detail/main/28/pipeline/
https://jenkins.backbase.eu/job/Entitlements/job/LE/job/legalentity-integration-service/job/SEGM-558-migrate-to-boat/1/
These builds pass locally, but fail on Jenkins, I was able to reproduce the issue locally only with clean maven local repo.

revert conflicting dependency update
