README.md
boat-diff/pom.xml
boat-engine/pom.xml
boat-maven-plugin/pom.xml
boat-maven-plugin/src/main/java/com/backbase/oss/boat/AbstractRamlToOpenApi.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/CodeGenMojo.java
boat-maven-plugin/src/main/templates/htmlDocs2/index.mustache
boat-maven-plugin/src/main/templates/htmlDocs2/paramB.mustache
boat-terminal/pom.xml
pom.xml
tests/pom.xml

• Applied the fix from this PR: https://github.com/OpenAPITools/openapi-generator/pull/5643/files
• Corrections in README.md
• bumped the version up

Fixes HTML2 docs template;

---

README.md
boat-diff/pom.xml
boat-engine/pom.xml
boat-maven-plugin/pom.xml
boat-maven-plugin/src/main/templates/Java/libraries/resttemplate/api.mustache
boat-maven-plugin/src/main/templates/Java/libraries/resttemplate/pom.mustache
boat-maven-plugin/src/main/templates/Java/pom.mustache
boat-terminal/pom.xml
pom.xml
tests/pom.xml

Release 0.1.5

---

boat-maven-plugin/README.md
boat-maven-plugin/src/main/java/com/backbase/oss/boat/BundleMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/CodeGenMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/DecomposeMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/DiffMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/ExportBomMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/ExportDependenciesMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/ExportMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/RemoveDeprecatedMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/ValidateMojo.java

Update the mojo javadoc and the readme for the maven plugin.

Add mojo class descriptions.

---

boat-engine/src/main/java/com/backbase/oss/boat/Exporter.java

Unwanted changes had crept in Exporter.java. Reverted.

fix: revert unwanted changes in Exporter.java

---

README.md
boat-engine/src/main/java/com/backbase/oss/boat/DirectoryExploder.java
boat-engine/src/main/java/com/backbase/oss/boat/example/NamedExample.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/ExampleExtractors.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/OpenAPIExtractor.java
boat-engine/src/test/java/com/backbase/oss/boat/transformers/ExampleExtractorsTest.java
boat-terminal/src/main/java/com/backbase/oss/boat/BoatTerminal.java

Add example extractor info to release notes for 0.1.6, as well as Javadocs for the same functionality

Add example extractor info to release notes for 0.1.6

---

boat-maven-plugin/README.md

docs: add generate-spring-boot-embedded, generate-rest-template-embedded and generate-webclient-embedded mojos

docs: add 3 new code generation mojos

---

boat-maven-plugin/src/main/templates/htmlDocs2/index.mustache

Remove Boat! from head title and remove second unnecessary subtitle and horizontal line

Clean up titles

---

README.md
boat-diff/pom.xml
boat-engine/pom.xml
boat-engine/src/main/java/com/backbase/oss/boat/Exporter.java
boat-engine/src/test/java/com/backbase/oss/boat/ExporterTest.java
boat-maven-plugin/pom.xml
boat-terminal/pom.xml
pom.xml
tests/pom.xml

Release 0.2.6 - Ensure extensions are in lower hyphen case

---

boat-maven-plugin/src/main/templates/htmlDocs2/index.mustache
boat-maven-plugin/src/main/templates/htmlDocs2/styles.mustache

**Changes:**
- Improves left navigation
- fixes text overflowing
- Adds a section for particular Bb extensions which is missing from the API documentation
Before:
After:

Left navigation improvements

---

.gitignore
boat-maven-plugin/src/main/java/com/backbase/oss/boat/GenerateMojo.java

Support 'addTestCompileSourceRoot'

added "addTestCompileSourceRoot"

---

README.md
boat-scaffold/src/main/templates/JavaSpringBoat/pojo.mustache

The `abstract` modifier was missing from the generated classes

Fixed x-abstract

---

boat-engine/src/main/java/com/backbase/oss/boat/transformers/DereferenceComponentsPropertiesTransformer.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/OpenApiStreamUtil.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/UnAliasTransformer.java
boat-engine/src/test/java/com/backbase/oss/boat/transformers/DereferenceComponentsPropertiesTransformerTest.java
boat-engine/src/test/resources/openapi/decomposer-test-api/openapi.yaml
boat-maven-plugin/src/main/java/com/backbase/oss/boat/GenerateMojo.java

Add DereferenceComponentsPropertiesTransformer (that does a bit extra)
Fix recursive referencing in UnAliasTransformer

Add DereferenceComponentsPropertiesTransformer (Plus minor fixes)

---

boat-scaffold/src/main/templates/boat-docs/css_json_schema_view.mustache
boat-scaffold/src/main/templates/boat-docs/fonts.mustache
boat-scaffold/src/main/templates/boat-docs/index.mustache
boat-scaffold/src/main/templates/boat-docs/js_example_formatter.mustache
boat-scaffold/src/main/templates/boat-docs/param.mustache
boat-scaffold/src/main/templates/boat-docs/paramB.mustache
boat-scaffold/src/main/templates/boat-docs/styles.mustache

- Updated the styles for the request bodies
- Added examples column 
- Updated left navigation to show the summary if present instead of operationId

[WIP] Feature/html2 styles

---

boat-engine/src/main/java/com/backbase/oss/boat/DirectoryExploder.java
boat-engine/src/test/java/com/backbase/oss/boat/TransformerTests.java
boat-terminal/.gitignore
boat-terminal/pom.xml
boat-terminal/src/main/java/com/backbase/oss/boat/BoatTerminal.java
boat-terminal/src/main/resources/logback.xml
boat-terminal/src/test/java/com/backbase/oss/boat/BoatTerminalTest.java

A new and modern Boat Terminal...

modernised the boat terminal

---

boat-scaffold/src/main/templates/boat-docs/css_json_schema_view.mustache
boat-scaffold/src/main/templates/boat-docs/index.mustache
boat-scaffold/src/main/templates/boat-docs/paramB.mustache
boat-scaffold/src/main/templates/boat-docs/styles.mustache

Adds css grid
Adds right hand examples

Removes floats

---

boat-maven-plugin/src/main/java/com/backbase/oss/boat/LintMojo.java
boat-maven-plugin/src/test/java/com/backbase/oss/boat/LintMojoTests.java
boat-maven-plugin/src/test/resources/oas-examples/no-lint-warnings.yaml

The linter would happily congratulate you on a warning free spec... and fail the build.

LintMojo fails on warning always fails - even when there are no warnings.

---

boat-scaffold/src/main/templates/boat-docs/css_json_schema_view.mustache
boat-scaffold/src/main/templates/boat-docs/css_response.mustache
boat-scaffold/src/main/templates/boat-docs/paramB.mustache
boat-scaffold/src/main/templates/boat-docs/response.mustache

Fixes text overflowing

---

README.md
boat-engine/pom.xml
boat-engine/src/main/java/com/backbase/oss/boat/transformers/AdditionalPropertiesAdder.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/Bundler.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/CaseFormatTransformer.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/Decomposer.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/Deprecator.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/DereferenceComponentsPropertiesTransformer.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/LicenseAdder.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/Normaliser.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/SpecVersionTransformer.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/Transformer.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/UnAliasTransformer.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/VendorExtensionFilter.java
boat-engine/src/main/java/com/backbase/oss/boat/transformers/bundler/BoatCache.java
boat-engine/src/test/java/com/backbase/oss/boat/transformers/VendorExtensionFilterTest.java
boat-engine/src/test/resources/openapi/extension-filter/openapi.yaml
boat-maven-plugin/README.md
boat-maven-plugin/pom.xml
boat-maven-plugin/src/main/java/com/backbase/oss/boat/BundleMojo.java
boat-maven-plugin/src/test/java/com/backbase/oss/boat/BundleMojoTest.java
boat-terminal/pom.xml
pom.xml

- filter vendor extensions
- added includes to boat:bundle (defaults to `*.yaml`)

Added vendor extension filter

---

README.md
boat-maven-plugin/src/main/java/com/backbase/oss/boat/GenerateMojo.java
boat-scaffold/src/main/java/com/backbase/oss/codegen/java/BoatJavaCodeGen.java
boat-scaffold/src/main/java/com/backbase/oss/codegen/java/BoatSpringCodeGen.java
boat-scaffold/src/main/templates/boat-java/api.mustache
boat-scaffold/src/main/templates/boat-java/libraries/resttemplate/ApiClient.mustache
boat-scaffold/src/main/templates/boat-java/libraries/resttemplate/api.mustache
boat-scaffold/src/main/templates/boat-java/pojo.mustache
boat-scaffold/src/test/java/com/backbase/oss/codegen/java/BoatJavaCodeGenTests.java

Added more options to Java client

---

boat-scaffold/src/main/templates/boat-angular/api.service.mustache

Generate *Url methods that return the URL for an endpoint

---

boat-scaffold/src/main/java/com/backbase/oss/codegen/angular/BoatAngularCodegenOperation.java
boat-scaffold/src/main/java/com/backbase/oss/codegen/angular/BoatAngularGenerator.java

This is an alternative solution to #133 
There is definitely some logic that could be moved into this new class,
but I left the change minimal because I'm not sure yet if this will be
moved up to a more general location (i.e. outside the angular
generator) and didn't want to add angular/typescript specific changes.

Wrap `CodegenOperation` to add extra `pattern` field

---

boat-engine/src/main/java/com/backbase/oss/boat/transformers/bundler/ExamplesProcessor.java
boat-engine/src/test/java/com/backbase/oss/boat/transformers/BundlerTests.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/GenerateMojo.java

Fix building on Windows.

---

rules.md

Added documentation for new lint rules, and documentation on how to enable linting with boat and how to use it.

Befound 120 boat lint document new rules

---

boat-quay/boat-quay-rules/src/main/resources/boat.conf

Aiming to adopt within 3 months from the release
https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.0

chore: update OpenAPI version according to our policies

---

boat-engine/src/main/java/com/backbase/oss/boat/transformers/bundler/ExamplesProcessor.java
boat-scaffold/src/main/java/com/backbase/oss/codegen/doc/BoatExample.java

Fix some issues with examples

---

README.md
boat-maven-plugin/README.md
boat-maven-plugin/src/main/java/com/backbase/oss/boat/radio/RadioMojo.java
boat-maven-plugin/src/test/java/com/backbase/oss/boat/radio/RadioMojoTests.java

Properties w.r.t boat-bay-server were made unique so that it could be used via cli.
Change the default for boat-bay error to false.

Made property unique

---

boat-maven-plugin/src/test/java/com/backbase/oss/boat/LintMojoTests.java
boat-quay/boat-quay-lint/pom.xml
boat-quay/boat-quay-rules/pom.xml

Update zally to 2.1.0; update kotlin to 1.4.10; exclude one modified rule in test.

Update zally to 2.1.0; update kotlin to 1.4.10.

---

boat-scaffold/src/main/java/com/backbase/oss/codegen/angular/BoatAngularGenerator.java
boat-scaffold/src/test/java/com/backbase/oss/codegen/angular/MultipleTagsTests.java
boat-scaffold/src/test/resources/oas-examples/petstore-multiple-tags.yaml

#318 Only process first tag and ignore the rest

Remove multiple tags on boat angular

---

boat-scaffold/src/main/java/com/backbase/oss/codegen/angular/BoatAngularGenerator.java
boat-scaffold/src/test/java/com/backbase/oss/codegen/angular/BoatAngularTemplatesTests.java

Description:
BoatAngularGenerator: added dependency versions to support angular@14. 
https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3
typescript and node js version : https://github.com/angular/angular/releases/tag/14.0.0

BoatAngularGenerator:[WF-848] Update to Angular 14

---

boat-engine/src/main/java/com/backbase/oss/boat/DirectoryExploder.java
boat-engine/src/test/java/com/backbase/oss/boat/AbstractBoatEngineTestBase.java
boat-engine/src/test/java/com/backbase/oss/boat/transformers/BundlerTests.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/BundleMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/DecomposeMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/GenerateMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/RemoveDeprecatedMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/diff/BatchOpenApiDiff.java
boat-maven-plugin/src/test/java/com/backbase/oss/boat/transformers/AbstractBoatEngineTests.java

on platforms with a default encoding apart from UTF8

Fix issue with non-UTF8-encoded YAML files

---

boat-maven-plugin/src/main/java/com/backbase/oss/boat/GenerateFromDirectoryDocMojo.java
boat-maven-plugin/src/test/java/com/backbase/oss/boat/GeneratorTests.java

This PR fixes https://github.com/Backbase/backbase-openapi-tools/issues/239

Bugfix: issue 239

---

boat-maven-plugin/README.md
boat-maven-plugin/src/main/java/com/backbase/oss/boat/AbstractGenerateMojo.java
boat-maven-plugin/src/test/java/com/backbase/oss/boat/GenerateMojoTests.java
boat-scaffold/src/test/java/com/backbase/oss/codegen/java/BoatSpringTemplatesTests.java
boat-scaffold/src/test/resources/boat-spring/openapi.yaml

PR to solve https://github.com/Backbase/backbase-openapi-tools/issues/604
By default:
`"containerDefaultToNull", "false"`
Possibility to override it in boat plugin configuration:
```xml
<configuration>
...
<configOptions>
<containerDefaultToNull>true</containerDefaultToNull>
</configOptions>
...
</configuration>
```

Issue 604: containerDefaultToNull set to false by default

---

boat-scaffold/src/main/java/com/backbase/oss/codegen/java/BoatSpringCodeGen.java
boat-scaffold/src/test/java/com/backbase/oss/codegen/java/BoatSpringCodeGenTests.java

Addresses https://github.com/Backbase/backbase-openapi-tools/issues/615

Rewrite the validated fully qualified classname

---

README.md
boat-scaffold/src/main/templates/boat-spring/collectionDataTypeParam.mustache
boat-scaffold/src/test/java/com/backbase/oss/codegen/java/BoatSpringCodeGenTests.java
boat-scaffold/src/test/resources/boat-spring/openapi.yaml

Fix for incorrectly generated enum type param on collection items of RequestParams

Enum param validation

---

README.md
boat-scaffold/src/main/templates/boat-java/libraries/resttemplate/api.mustache
boat-scaffold/src/test/java/com/backbase/oss/codegen/java/BoatJavaCodeGenTests.java

Fixes https://github.com/Backbase/backbase-openapi-tools/issues/630

Fix createApiComponent option in resttemplate is ignored

---

boat-maven-plugin/src/main/java/com/backbase/oss/boat/AbstractGenerateMojo.java
boat-maven-plugin/src/main/java/com/backbase/oss/boat/GenerateSpringBootEmbeddedMojo.java
boat-maven-plugin/src/test/java/com/backbase/oss/boat/GenerateMojoTests.java
boat-scaffold/src/main/java/com/backbase/oss/codegen/java/BoatSpringCodeGen.java
boat-scaffold/src/main/templates/boat-spring/libraries/spring-boot/BigDecimalCustomSerializer.mustache
boat-scaffold/src/main/templates/boat-spring/libraries/spring-boot/pom-sb3.mustache
boat-scaffold/src/test/java/com/backbase/oss/codegen/java/BoatSpringCodeGenTests.java
boat-scaffold/src/test/java/com/backbase/oss/codegen/java/BoatSpringTemplatesTests.java
boat-scaffold/src/test/resources/boat-spring/openapi.yaml

Solution for https://github.com/Backbase/backbase-openapi-tools/issues/635
Resolved in similar way as here https://github.com/OpenAPITools/openapi-generator/blob/v6.6.0/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L1470

Serialize BigDecimal with string of number format into string

---

boat-scaffold/src/main/templates/boat-swift5/AnyCodable.swift.mustache
boat-scaffold/src/main/templates/boat-swift5/Extensions.mustache
boat-scaffold/src/main/templates/boat-swift5/api_operation_parameter_model.mustache

To ensure smooth transition, we seek to update the templates to have them match all the internal templates.

Update Swift templates

---

boat-scaffold/src/main/templates/boat-android/api_operation_parameter_model.mustache

Updated mustache templates

---

boat-scaffold/src/main/templates/boat-spring/beanValidationCore.mustache
boat-scaffold/src/test/resources/boat-spring/openapi.yaml

Solves https://github.com/Backbase/backbase-openapi-tools/issues/757

Fix Email annotation; copied from ootb spring boot templates

---

boat-maven-plugin/src/it/example/pom.xml
boat-scaffold/src/main/templates/boat-java/libraries/microprofile/enumOuterClass.mustache
boat-scaffold/src/main/templates/boat-java/libraries/resttemplate/ApiClient.mustache
boat-scaffold/src/main/templates/boat-java/libraries/resttemplate/auth/HttpBasicAuth.mustache
boat-scaffold/src/main/templates/boat-java/libraries/resttemplate/auth/HttpBearerAuth.mustache
boat-scaffold/src/main/templates/boat-java/libraries/webclient/ApiClient.mustache
boat-scaffold/src/main/templates/boat-java/libraries/webclient/auth/HttpBasicAuth.mustache
boat-scaffold/src/main/templates/boat-java/libraries/webclient/auth/HttpBearerAuth.mustache
boat-scaffold/src/main/templates/boat-java/modelEnum.mustache
boat-scaffold/src/main/templates/boat-java/modelInnerEnum.mustache
boat-scaffold/src/main/templates/boat-spring/enumClass.mustache
boat-scaffold/src/main/templates/boat-spring/enumOuterClass.mustache
boat-scaffold/src/main/templates/boat-spring/libraries/spring-boot/pom-sb3.mustache
boat-scaffold/src/main/templates/boat-spring/libraries/spring-boot/pom.mustache

- Replaced usage of deprecated Spring classes
- Fixed some small code inspection warnings

Issue 656 deprecated code

---

boat-scaffold/src/main/templates/boat-android/api.mustache
boat-scaffold/src/main/templates/boat-android/build.gradle.mustache
boat-scaffold/src/main/templates/boat-android/data_class.mustache

* Removed commonUtils from Boat Android

Removed commonUtils from Boat Android
